---
title: "R Notebook"
output: html_notebook
---



```{r}
HIRN_data <- SetIdent(HIRN_data, value = HIRN_data$subtype2)

levels(HIRN_data) <- c("Hs-Endocrine 1", "Hs-Endocrine 2", "Hs-Acinar", "Hs-PDCs", "Hs-Activated PSCs", "Hs-Quiescent PSCs", "Hs-Endothelial", "Hs-Immune", "Hs-Unclassified")

D1 <- DimPlot(HIRN_data)
ggsave(plot = D1, filename = "HIRN_data Dimplot.tiff", path = "H:/LAB 20 IIT K/M.TECH THESIS/HIRN Data/Sheets/Hs-First fig/",height = 5, width = 7, device = "tiff", dpi = 600)

D2 <- DimPlot(HIRN_data, split.by = "condition")+NoLegend()
ggsave(plot = D2, filename = "HIRN_data Dimplot split.by.cond.tiff", path = "H:/LAB 20 IIT K/M.TECH THESIS/HIRN Data/Sheets/Hs-First fig/",height = 5, width = 15, device = "tiff", dpi = 600)

D3 <- DimPlot(HIRN_data, label = T, repel = T, label.size = 2.5)
ggsave(plot = D3, filename = "HIRN_data Dimplot labeled.tiff", path = "H:/LAB 20 IIT K/M.TECH THESIS/HIRN Data/Sheets/Hs-First fig/",height = 5, width = 7, device = "tiff", dpi = 600)

# F1 <- FeaturePlot(HIRN_data, features = "INS")+NoLegend()
# ggsave(plot = F1, filename = "HIRN_data Featureplot INS.tiff", path = "H:/LAB 20 IIT K/M.TECH THESIS/HIRN Data/Sheets/Hs-Alpha/",height = 5, width = 5, device = "tiff", dpi = 600)
# 
# F2 <- FeaturePlot(HIRN_data, features = "GCG")+NoLegend()
# ggsave(plot = F2, filename = "HIRN_data Featureplot GCG.tiff", path = "H:/LAB 20 IIT K/M.TECH THESIS/HIRN Data/Sheets/Hs-Alpha/",height = 5, width = 5, device = "tiff", dpi = 600)

hue_pal()(9)

color_pallete <- c("#F8766D","#F8766D",#Hs.Endocrine 1 INS+
  "#D39200","#D39200","#D39200",#Hs.Endocrine 2 GCG+
  "#93AA00","#93AA00","#93AA00",#Hs.Acinar
  "#00BA38", "#00BA38", "#00BA38",#Hs.PDCs
  "#00C19F","#00C19F",#Hs-Activated PSCs
  "#00B9E3", "#00B9E3",#Hs-Quiescent PSCs 
  "#619CFF", "#619CFF", "#619CFF",#Hs-Endothelial
  "#DB72FB", "#DB72FB")#Hs.Immune


marker_genes <- c("INS", "RBP4", "GCG", "CHGA", "TTR", "CTRB1", "PRSS1", "CELA3A", "MMP7", "KRT18", "KRT19","TIMP3", "SFRP2", "RGS5", "ADIRF",  "PECAM1", "PLVAP", "GNG11", "CD74", "HLA-DRA")

V1 <- VlnPlot(HIRN_data, features = marker_genes, stack = T, flip = T, cols = color_pallete)+theme(axis.text.x = element_text(size=11, angle=45, hjust=1, color="black"),
        axis.text.y = element_text(size=11, color="black"),
        axis.title = element_text(size=14))+NoLegend()

ggsave(plot = V1, filename = "HIRN_data vlnplot.tiff", path = "H:/LAB 20 IIT K/M.TECH THESIS/HIRN Data/Sheets/Hs-First fig/",height = 12, width = 6, device = "tiff", dpi = 600)
```
  





```{r}
#Hs.Alpha 1 T2D and obese up
Stress_celldeath <- c("HSPA5", "GADD45A", "HSP90AA1", "MAP1LC3B", "PPP1R15A", "TNFRSF12A", "NEAT1", "JUNB", "SOD2")

#Hs.Alpha 1 control up
ETC_mito_TCA_OXPHOS <- c("UQCRQ", "NDUFB2", "NDUFS6", "NDUFA3", "ROMO1", "ATP5F1E", "ATP5ME", "DPYSL2", "ALDH1A1", "TMEM14A")

Translation <- c("RPS17", "RPS26", "RPL31", "RPS17", "RPL41", "RPLP2", "HMGN2", "RPS10", "POLR2L", "RPL34")

Nucleobase_metabolicProcess <- c("ATP5E", "DPYSL2", "ATP5F1E", "ALDH1A1")

all_genes <- rev(unique(c(Stress_celldeath, ETC_mito_TCA_OXPHOS, Translation)))

Dot1 <- DotPlot(HIRN_data, assay = "RNA", features = all_genes, scale.min = 0, scale.max = 100, dot.scale = 15, cols = c("#33AEFF", "#FF5733"), idents = idents.to.use) +theme(axis.text.x = element_text(size=11, angle=45, hjust=1, color="black"),
        axis.text.y = element_text(size=11, color="black"),
        axis.title = element_text(size=14), legend.box = "left", legend.box.just = "left", legend.position = "right", legend.title = element_text(size = 11), legend.text  = element_text(size=8))+coord_flip()+xlab(" ")+ylab(" ")


ggsave(plot = Dot1, filename = "Hs.Alpha 1 pathway dotplot.tiff", path = "H:/LAB 20 IIT K/M.TECH THESIS/HIRN Data/Sheets/Hs-Alpha/",height = 14, width = 5, device = "tiff", dpi = 600)

```

```{r}

levels(Hs.Alpha) <- c("Hs-Alpha 1_Control", "Hs-Alpha 1_Obese", "Hs-Alpha 1_T2D", "Hs-Alpha 2_Control", "Hs-Alpha 2_Obese", "Hs-Alpha 2_T2D")

idents.to.use <- c("Hs-Alpha 1_Control", "Hs-Alpha 1_Obese", "Hs-Alpha 1_T2D")

idents.to.use <-  c("Hs-Alpha 1_Control", "Hs-Alpha 1_Obese", "Hs-Alpha 1_T2D", "Hs-Alpha 2_Control", "Hs-Alpha 2_Obese", "Hs-Alpha 2_T2D")

Dot1 <- DotPlot(HIRN_data, assay = "RNA", features = unique(c(Stress_celldeath, ETC_mito_TCA_OXPHOS, Translation)), scale.min = 0, scale.max = 100, dot.scale = 15, cols = c("#33AEFF", "#FF5733"), idents = idents.to.use) +theme(axis.text.x = element_text(size=11, angle=45, hjust=1, color="black"),
        axis.text.y = element_text(size=11, color="black"),
        axis.title = element_text(size=14), legend.box = "left", legend.box.just = "left", legend.position = "right", legend.title = element_text(size = 11), legend.text  = element_text(size=8))+coord_flip()+xlab(" ")+ylab(" ")



```

```{r}
Dot1 <- DotPlot(Hs.Alpha, assay = "RNA", features = unique(c(Stress_celldeath)),scale = F, scale.min = 0, scale.max = 100, dot.scale = 15, cols = c("#33AEFF", "#FF5733"), idents = idents.to.use) +theme(axis.text.x = element_text(size=11, angle=45, hjust=1, color="black"),
        axis.text.y = element_text(size=11, color="black"),
        axis.title = element_text(size=14), legend.box = "left", legend.box.just = "left", legend.position = "right", legend.title = element_text(size = 11), legend.text  = element_text(size=8))+coord_flip()


Dot2 <- DotPlot(Hs.Alpha, assay = "RNA", features = unique(c(Stress_celldeath)), scale.min = 0, scale.max = 100, dot.scale = 15, cols = c("cyan", "red"), idents = idents.to.use) +theme(axis.text.x = element_text(size=11, angle=45, hjust=1, color="black"),
        axis.text.y = element_text(size=11, color="black"),
        axis.title = element_text(size=14), legend.box = "left", legend.box.just = "left", legend.position = "right", legend.title = element_text(size = 11), legend.text  = element_text(size=8))+coord_flip()+xlab(" ")+ylab(" ")

```

####################################################################################################
Hs.Alpha 2
```{r}

HIRN_data <- SetIdent(HIRN_data, value = HIRN_data$cellchat_states.detailed.condition)
levels(HIRN_data) <- levels(HIRN_data) %>% sort()
#Hs.Alpha 2 T2D
Peptidase_act <- c("PRSS1", "CELA2A", "PRSS2", "CPA1", "CPB1", "CPB1", "CELA3A", "CELA3B", "CTRC", "CTRB2", "CTRB1", "PRSS3", "PLA2G1B", "REG1A", "REG1B", "TAF10", "PNLIP", "CLPS", "CEL")

Mito_TCA_ETC <- c("LDHA", "NDUFB8", "NDUFV2", "NDUFA13", "ATP5PD", "NDUFB3", "SMDT1", "ATP5PD", "UQCC2", "MRPL20")

Hormone_act <- c("INS", "SST", "IAPP", "GCG", "PAX6")


all_genes <- rev(unique(c(Peptidase_act, Mito_TCA_ETC)))


```

```{r}
idents.to.use <- c("Hs-Alpha 2_Control", "Hs-Alpha 2_Obese", "Hs-Alpha 2_T2D")

#idents.to.use <-  c("Hs-Alpha 1_Control", "Hs-Alpha 1_Obese", "Hs-Alpha 1_T2D", "Hs-Alpha 2_Control", "Hs-Alpha 2_Obese", "Hs-Alpha 2_T2D")

Dot1 <- DotPlot(HIRN_data, assay = "RNA", features = all_genes, scale.min = 0, scale.max = 100, dot.scale = 15, cols = c("#33AEFF", "#FF5733"), idents = idents.to.use) +theme(axis.text.x = element_text(size=11, angle=45, hjust=1, color="black"),
        axis.text.y = element_text(size=11, color="black"),
        axis.title = element_text(size=14), legend.box = "left", legend.box.just = "left", legend.position = "right", legend.title = element_text(size = 11), legend.text  = element_text(size=8))+coord_flip()+xlab(" ")+ylab(" ")


ggsave(plot = Dot1, filename = "Hs.Alpha 2 pathway dotplot 1.tiff", path = "H:/LAB 20 IIT K/M.TECH THESIS/HIRN Data/Sheets/Hs-Alpha/",height = 14, width = 5, device = "tiff", dpi = 600)
```


```{r}
#Hs.Alpha 2 Obese


Glucose_intolrance <- c("MT-ND6", "MT-ATP6", "PRSS2", "MT-ND5", "MT-CYB", "MT-ND1", "MT-CO3", "CEL", "MT-ND3", "FOS", "MT-CO1", "CPE", "CPA1", "PAX6", "HLA-C", "B2M", "HLA-B", "EPCAM", "HLA-A", "SCG5")


Response_to_stress <- c("NEAT1", "SOD2", "APP", "IER3", "HSPA5", "HSP90AA1", "IL6ST", "TMBIM6", "RB1CC1", "B2M", "GADD45A", "HLA-B", "HLA-A")

#Translation_peptidebiosynthesis <- c("RPS26", "RPS10", "RPL34", "RPL3", "RPL41", "RPS17", "RPL31", "RPL35", "RPS8", "RPL36", "RPS28", "RPL28", "RPS11", "RPL36AL", "RPL37A", "RPS20", "RPS15", "RPS4X", "RPL21", "RPS12", "RPS3A", "RPLP2", "RPL35A", "RPS15A", "RPLP1", "UBA52", "RPL32", "RPS23", "RPL27A", "RPL23", "RPL12", "RPL39", "RPL13", "RPL11", "RPL22", "RPS9", "RPS14", "RPS18", "RPL26", "RPL13A", "RPS25", "RPS25", "RPS27", "RPS5", "RPS21", "RPL36A")

all_genes <- rev(unique(c( Glucose_intolrance, Response_to_stress)))
```

```{r}
idents.to.use <- c("Hs-Alpha 2_Control", "Hs-Alpha 2_Obese", "Hs-Alpha 2_T2D")

#idents.to.use <-  c("Hs-Alpha 1_Control", "Hs-Alpha 1_Obese", "Hs-Alpha 1_T2D", "Hs-Alpha 2_Control", "Hs-Alpha 2_Obese", "Hs-Alpha 2_T2D")

Dot1 <- DotPlot(HIRN_data, assay = "RNA", features = all_genes, scale.min = 0, scale.max = 100, dot.scale = 15, cols = c("#33AEFF", "#FF5733"), idents = idents.to.use) +theme(axis.text.x = element_text(size=11, angle=45, hjust=1, color="black"),
        axis.text.y = element_text(size=11, color="black"),
        axis.title = element_text(size=14), legend.box = "left", legend.box.just = "left", legend.position = "right", legend.title = element_text(size = 11), legend.text  = element_text(size=8))+coord_flip()+xlab(" ")+ylab(" ")


ggsave(plot = Dot1, filename = "Hs.Alpha 2 pathway dotplot 2.tiff", path = "H:/LAB 20 IIT K/M.TECH THESIS/HIRN Data/Sheets/Hs-Alpha/",height = 13, width = 5, device = "tiff", dpi = 600)
```


```{r}
Translation_peptidebiosynthesis <- c("RPS26", "RPL34", "RPL3", "RPL41", "RPS17", "RPL31", "RPL35", "RPS8", "RPL36", "RPS28", "RPL28", "RPS11", "RPL36AL", "RPL37A", "RPS20", "RPS15", "RPS4X", "RPL21", "RPS12", "RPS3A", "RPLP2", "RPL35A", "RPS15A", "RPLP1")

all_genes <- unique(rev(Translation_peptidebiosynthesis))

Dot1 <- DotPlot(HIRN_data, assay = "RNA", features = all_genes, scale.min = 0, scale.max = 100, dot.scale = 15, cols = c("#33AEFF", "#FF5733"), idents = idents.to.use) +theme(axis.text.x = element_text(size=11, angle=45, hjust=1, color="black"),
        axis.text.y = element_text(size=11, color="black"),
        axis.title = element_text(size=14), legend.box = "left", legend.box.just = "left", legend.position = "right", legend.title = element_text(size = 11), legend.text  = element_text(size=8))+coord_flip()+xlab(" ")+ylab(" ")


ggsave(plot = Dot1, filename = "Hs.Alpha 2 pathway dotplot 3.tiff", path = "H:/LAB 20 IIT K/M.TECH THESIS/HIRN Data/Sheets/Hs-Alpha/",height = 13, width = 5, device = "tiff", dpi = 600)
```


####################################################################################################

Hs.Beta 1
```{r}
HIRN_data <- SetIdent(HIRN_data, value =  HIRN_data$cellchat_states.detailed.condition)

#Hs.Beta 1 T2D
Exocrine_peptidase_ECM <- c("PRSS2", "PRSS1", "REG1B", "REG1A", "CSTB", "CPA1", "CELA2A", "CELA3A", "CTRB2", "CPB1", "PLA2G1B")

Ca_ion_transport <- c("TPT1",  "CALM1", "SMDT1", "ANXA2", "SELENOK","PLA2G1B")
 #obese
Hormone_act <- c("GCG", "SST","INS","TTR","VGF", "CHGB")

#Control
Translation <- c("RPS26", "RPL34", "RPL3", "RPS4X", "RPL36AL", "RPL36", "RPL31")

idents.to.use <-  c("Hs-Beta 1_Control", "Hs-Beta 1_Obese", "Hs-Beta 1_T2D")

all_genes <- rev(unique(c(Exocrine_peptidase_ECM, Ca_ion_transport, Hormone_act, Translation)))

Dot1 <- DotPlot(HIRN_data, assay = "RNA", features = all_genes, scale.min = 0, scale.max = 100, dot.scale = 15, cols = c("#33AEFF", "#FF5733"), idents = idents.to.use) +theme(axis.text.x = element_text(size=11, angle=45, hjust=1, color="black"),
        axis.text.y = element_text(size=11, color="black"),
        axis.title = element_text(size=14), legend.box = "left", legend.box.just = "left", legend.position = "right", legend.title = element_text(size = 11), legend.text  = element_text(size=8))+coord_flip()+xlab(" ")+ylab(" ")


ggsave(plot = Dot1, filename = "Hs.Beta 1 pathway dotplot.tiff", path = "H:/LAB 20 IIT K/M.TECH THESIS/HIRN Data/Sheets/Hs-Beta/",height = 15, width = 5, device = "tiff", dpi = 600)
```





```{r}
levels(HIRN_data) <- levels(HIRN_data) %>% sort()

#Hs.Beta 2 T2D
Immune_response <- c("PLCG2", "CD99", "JUND", "HSP90AA1","SELENOK")
Homeostasis <- c("HSPA5", "GNAS")
Mito <- c("HSPA5", "AGPAT5", "MT-ND4L", "HSP90AA1", "MT-ATP8")
Hormone_act <- c("SST", "TTR", "IAPP", "NPY", "VGF", "GCG")

#Hs.Beta 2 Obese
Negative_reg_cell_death <- c("IER3", "SCG2", "PKD4", "SOD2")

#Hs.Beta 2 Obese
Translation_peptidebiosynthesis <- c("RPS10", "RPS26", "RPL34", "RPL41", "RPL31", "RPL35")

idents.to.use <-  c("Hs-Beta 2_Control", "Hs-Beta 2_Obese", "Hs-Beta 2_T2D")

all_genes <- rev(unique(c(Immune_response, Homeostasis, Mito, Hormone_act, Negative_reg_cell_death, Translation_peptidebiosynthesis)))

Dot1 <- DotPlot(HIRN_data, assay = "RNA", features = all_genes, scale.min = 0, scale.max = 100, dot.scale = 15, cols = c("#33AEFF", "#FF5733"), idents = idents.to.use) +theme(axis.text.x = element_text(size=11, angle=45, hjust=1, color="black"),
        axis.text.y = element_text(size=11, color="black"),
        axis.title = element_text(size=14), legend.box = "left", legend.box.just = "left", legend.position = "right", legend.title = element_text(size = 11), legend.text  = element_text(size=8))+coord_flip()+xlab(" ")+ylab(" ")


ggsave(plot = Dot1, filename = "Hs.Beta 2 pathway dotplot.tiff", path = "H:/LAB 20 IIT K/M.TECH THESIS/HIRN Data/Sheets/Hs-Beta/",height = 15, width = 5, device = "tiff", dpi = 600)
```


```{r}
#Hs.Delta 1 T2D

YBX1_targets <- c("PLCG2", "NEAT1", "JUNB", "EGR1", "ZBTB20","IER2", "MAlAT1")

Peptidase_act_lipid_meta <- c("PRSS1", "CELA3A", "CPE", "CTSL", "CPA1", "USP9Y", "PRSS2", "CTRB1", "CLU", "CLPS", "HSD17B12", "ERG1", "ZBTB20")


#Hs.Delta 1 Obese
Cell_death <- c("BTG2", "MTRNR2L12", "PLCG2", "ASAH1")
extra <- c("NEAT1", "MALAT1")

#Hs.Delta 1 Control

Mito_OXPHOS <- c("NDUFS6", "NDUFA6", "COX7B", "COX6B1", "COX7A2", "COX7C", "TOMM7", "UQCR10", "POLR2F", "TOMM7")

#Hs.Delta 2 T2D

Hormone_act_secretion <- c( "SCG2", "MTRNR2L8", "CHGB", "PLA2G1B", "MTRNR2L12", "REG1A", "CEL", "CD81", "NPW", "CPE", "SYCN", "SPINK1", "PPY", "GCG", "INS","IAPP","TTR","NPY")

Peptidase_act <- c("PRSS1", "CPB1", "CPA1", "CELA2A", "CELA3A", "CTRB1", "CTRC", "PRSS2", "CELA3B", "CPE", "USP8", "USP7", "CYLD")

#Hs.Delta 2 Control
Mito <- c("TOMM7", "COX7A2", "COX5B", "NDUFB2", "NDUFA12", "ATP5MG", "UQCR11")

Peptide_biosynthesis <- c("RPS26", "RPL7", "RPL31", "RPS17", "RPS20", "RPL34", "RPLP2", "RPL23", "RPL28")

OXPHOS_ETC_TCA <- c("NDUFB2", "COX7C", "COX7A2", "NDUFA3", "UQCRQ", "ATP5F1E", "UQCR10", "MT-ND2", "ATP5ME", "UQCR11")

#Hs.Delta 2 Obese
Response_to_stress <- c("NEAT1", "NPY", "IER1", "SOD2", "FOXP1", "HLA-B", "GADD45A", "CAST", "DDIT3", "MTRNR2L12", "FOS", "ATF4")




idents.to.use <-  c("Hs-Delta 2_Control", "Hs-Delta 2_Obese", "Hs-Delta 2_T2D")

all_genes <- rev(unique(c(Peptidase_act, Hormone_act_secretion, Response_to_stress)))

all_genes <- rev(unique(c(Mito, OXPHOS_ETC_TCA, Peptide_biosynthesis)))
  
Dot1 <- DotPlot(HIRN_data, assay = "RNA", features = all_genes, scale.min = 0, scale.max = 100, dot.scale = 15, cols = c("#33AEFF", "#FF5733"), idents = idents.to.use) +theme(axis.text.x = element_text(size=11, angle=45, hjust=1, color="black"),
        axis.text.y = element_text(size=11, color="black"),
        axis.title = element_text(size=14), legend.box = "left", legend.box.just = "left", legend.position = "right", legend.title = element_text(size = 11), legend.text  = element_text(size=8))+coord_flip()+xlab(" ")+ylab(" ")


ggsave(plot = Dot1, filename = "Hs.Delta 2 pathway dotplot 2.tiff", path = "H:/LAB 20 IIT K/M.TECH THESIS/HIRN Data/Sheets/Hs-Delta/",height = 15, width = 5, device = "tiff", dpi = 600)
```


#Hs.Macrophages

```{r}
#Hs.Mac T2D

Leukocyte_chemotaxis <- c("IL1B", 'CXCL8', 'CXCL3', 'CCL3',  'PLA2G1B', 'CXCL2', 'CCL3L1', 'CCR7')
#HALLMARK_TNFA_SIGNALING_VIA_NFKB
 Inflammatory_response_NFKB_signaling <- c('IL1B', 'CXCL8', 'CCR7', 'EREG', 'NFKBIA', 'BTG2', 'IRF1', 'IL1B', 'CXCL8', 'CXCL3', 'CXCL2', 'SMOX', 'EREG', 'BTG2', 'JUN', 'LSP1', 'SLC7A11', 'IL1B', 'CXCL3', 'CCL4', 'CXCL2', 'PHLDA1', 'SOD2', 'G0S2', 'NFKBIA', 'BTG2', 'JUN', 'IRF1', 'IER3', 'CEBPB', 'CD44', 'PPP1R15A',  'PDE4B', 'GADD45A')

 
 #Hs.Mac obese
 
 Interlukin_signaling <- c('IL1B', 'CXCL8', 'HSP90B1', 'SOD2', 'CCL3', 'JUN', 'CXCL2', 'CCL3L1')



#control

Antigen_presentation_processing <- c('HLA-DPB1', 'HLA-DRA',' HLA-DRB1', 'CD74', 'HLA-DMA', 'HLA-DPA1', 'HLA-DQB1')

 Translation <- c('RPS17', 'RPS26', 'RPL31', 'RPL7', 'RPL36A')
 
 
 

idents.to.use <-  c("Hs-Macrophages_Control", "Hs-Macrophages_Obese", "Hs-Macrophages_T2D")

all_genes <- rev(unique(c(Leukocyte_chemotaxis, Inflammatory_response_NFKB_signaling, Interlukin_signaling,  Antigen_presentation_processing, Translation)))


Dot1 <- DotPlot(HIRN_data, assay = "RNA", features = all_genes, scale.min = 0, scale.max = 100, dot.scale = 15, cols = c("#33AEFF", "#FF5733"), idents = idents.to.use) +theme(axis.text.x = element_text(size=11, angle=45, hjust=1, color="black"),
        axis.text.y = element_text(size=11, color="black"),
        axis.title = element_text(size=14), legend.box = "left", legend.box.just = "left", legend.position = "right", legend.title = element_text(size = 11), legend.text  = element_text(size=8))+coord_flip()+xlab(" ")+ylab(" ")



ggsave(plot = Dot1, filename = "Hs.Macrophages pathway dotplot 2.tiff", path = "H:/LAB 20 IIT K/M.TECH THESIS/HIRN Data/Sheets/Hs-Immune/",height = 18, width = 5, device = "tiff", dpi = 600)
```


```{r}
levels(HIRN_data) <- levels(HIRN_data) %>% sort() %>% rev()


DotPlot(HIRN_data, features = c("INS", "GCG", "SST","PPY"), idents = c("Hs-Alpha 1", "Hs-Alpha 2", "Hs-Beta 1", "Hs-Beta 2", "Hs-Beta 3", "Hs-Delta 1", "Hs-Delta 2", "Hs-Gamma"))

DotPlot(HIRN_data, features = c( "GCG", "INS","SST","PPY"), idents = c("Hs-Alpha 1", "Hs-Alpha 2", "Hs-Beta 1", "Hs-Beta 2", "Hs-Beta 3", "Hs-Delta 1", "Hs-Delta 2", "Hs-Gamma"))

V1 <- VlnPlot(HIRN_data, features = c( "GCG", "INS","SST","PPY"), idents = c("Hs-Alpha 1", "Hs-Alpha 2", "Hs-Beta 1", "Hs-Beta 2", "Hs-Beta 3", "Hs-Delta 1", "Hs-Delta 2", "Hs-Gamma"), stack = T, flip = T)+NoLegend()+xlab(" ")

D1 <- DotPlot(HIRN_data, features = c( "GCG", "INS","SST","PPY"), idents = c("Hs-Alpha 1", "Hs-Alpha 2", "Hs-Beta 1", "Hs-Beta 2", "Hs-Beta 3", "Hs-Delta 1", "Hs-Delta 2", "Hs-Gamma"), scale.min = 0, scale.max = 100, dot.scale = 15, cols = c("#33AEFF", "#FF5733"))+theme(axis.text.x = element_text(size=11, angle=45, hjust=1, color="black"),
        axis.text.y = element_text(size=11, color="black"),
        axis.title = element_text(size=14), legend.box = "left", legend.box.just = "left", legend.position = "right", legend.title = element_text(size = 11), legend.text  = element_text(size=8))+xlab(" ")+ylab(" ")

D1
ggsave(plot = D1, filename = "Hormone exp in subpops.tiff", path = "H:/LAB 20 IIT K/M.TECH THESIS/HIRN Data/Sheets/Hs-First fig/",height = 6, width = 6, device = "tiff", dpi = 600)

ggsave(plot = V1, filename = "Hormone exp in subpops vln.tiff", path = "H:/LAB 20 IIT K/M.TECH THESIS/HIRN Data/Sheets/Hs-First fig/",height = 8, width = 5, device = "tiff", dpi = 600)

  V1


```




```{r}
HIRN_data <- readRDS("H:/LAB 20 IIT K/HIRN-PANC DB/HIRN updated/Working rds/HIRN seurat processed and annotated wo juvenile JT.rds")
```

```{r}
HIRN_data <- SetIdent(HIRN_data, value = HIRN_data$subtype2)
D1 <- DimPlot(HIRN_data)
levels(HIRN_data) <- c( "Hs-Endocrine 1", "Hs-Endocrine 2"  ,"Hs-Acinar"   ,  "Hs-PDCs"  , "Hs-Activated PSCs", "Hs-Quiescent PSCs", "Hs-Endothelial" ,  "Hs-Immune"  , "Hs-Unclassified"  )


ggsave(plot = D1, filename = "HIRN plot embedding UMAP thesis.tiff", device = "tiff", path = "H:/LAB 20 IIT K/M.TECH THESIS/HIRN Data/Sheets/Hs-First fig/", width = 8, height = 7, dpi = 600)
```


```{r}

Hs.ATAC <- SetIdent(Hs.ATAC, value = Hs.ATAC$cor.states1)
levels(Hs.ATAC) <- c("Hs-Beta"   , "Hs-Alpha", "Hs-Delta",  "Hs-Acinar"  , "Hs-PDCs"  , "Hs-Activated PSCs", "Hs-Quiescent PSCs" ,    "Hs-Endothelial"   ,  "Hs-Immune" )

D2 <- DimPlot(Hs.ATAC)
ggsave(plot = D2, filename = "HIRN plot ATAC embedding UMAP thesis.tiff", device = "tiff", path = "H:/LAB 20 IIT K/Human Islets ATACseq JT/Hs.ATAC JT/Plots and sheets/Hs.ATACFirst fig JT/", width = 8, height = 7, dpi = 600)
```




Genes for vln plots     
```{r}


Hs.Alphavln <- c("PAX6", "IGFBP2", "MAFB", "CHGA", "CHGB", "INS","SST", "PRSS1", "CTRB2", "CELA3A2")
c(5,5)
Alpha.idents <- c("Hs-Alpha 1", "Hs-Alpha 2")



Hs.Endothelailvln <- c("COL4A1", "HSPG2", "JCAD", "INS", "REG1A", "SCG5", "CYTOR", "ANXA1", "KITLG", "ECE1", "CD74", "ICAM2")

c(4,4,4,4)

Hs.Betavln <- c("SST", "GCG", "PRSS2", "PRSS1", "REG1A", "PLCG2", "MT-CO1", "MT-CO2", "MT-ND2", "MT-ATP6", "NEAT1", "MALAT1", "MEG3", "NKTR")
c(5, 5, 4)
Beta.idents <- c("Hs-Beta 1", "Hs-Beta 2", "Hs-Beta 3")



Hs.Deltavln <- c("S100A10", "PLCG2", "NDUFS6", "SELENOW", "GCG", "INS", "REG1A", "PRSS2")
Delta.idents <- c("Hs-Delta 1", "Hs-Delta 2")

c(4,4)


Hs.Immunevln <- c("CD3D", "CCL5", "KLRB1", "TPSB2", "TPSAB1", "KIT", "CD68", "LYZ", "CXCL8", "HLA-DRA", "HLA-DPB1", "HLA-DPA1")

c(3,3,3,3)

```


