---
title: "R Notebook"
output: html_notebook
---


```{r}
library(devtools)
#install_github("arc85/singleseqgset")
library(singleseqgset)
#install.packages("msigdbr")
library(msigdbr)
library(heatmap3)
library(ggplot2)
library(fgsea)
library(Seurat)

c  <- gmtPathways("F:\\Jayesh_Human islets\\Human Islets atlas-HIRN\\HIRN-PANC DB\\HIRN updated\\Mm.GSEA/m2.cp.v0.3.symbols.gmt")
d  <- gmtPathways("F:\\Jayesh_Human islets\\Human Islets atlas-HIRN\\HIRN-PANC DB\\HIRN updated\\Mm.GSEA/m2.all.v0.3.symbols.gmt")
e  <- gmtPathways("F:\\Jayesh_Human islets\\Human Islets atlas-HIRN\\HIRN-PANC DB\\HIRN updated\\Mm.GSEA/m5.all.v0.3.symbols.gmt")
f  <- gmtPathways("F:\\Jayesh_Human islets\\Human Islets atlas-HIRN\\HIRN-PANC DB\\HIRN updated\\Mm.GSEA/mh.all.v0.3.symbols.gmt")

genesets <- c(c, d, e, f)

#HUMAN PATHWAYS

a  <- gmtPathways("D:\\Islet Project/fgsea/c2.cgp.v7.5.1.symbols.gmt")
e  <- gmtPathways("D:\\Islet Project/fgsea/c2.cp.biocarta.v7.5.1.symbols.gmt")
b  <- gmtPathways("D:\\Islet Project/fgsea/c2.cp.kegg.v7.5.1.symbols.gmt")
c  <- gmtPathways("D:\\Islet Project/fgsea/c2.cp.reactome.v7.5.1.symbols.gmt")
d  <- gmtPathways("D:\\Islet Project/fgsea/c2.cp.wikipathways.v7.5.1.symbols.gmt")
f  <- gmtPathways("D:\\Islet Project/fgsea/c5.go.bp.v2023.2.Hs.symbols.gmt")
g  <- gmtPathways("D:\\Islet Project/fgsea/c5.go.cc.v2023.2.Hs.symbols.gmt")
h  <- gmtPathways("D:\\Islet Project/fgsea/c5.go.mf.v2023.2.Hs.symbols.gmt")

genesets <- c(a, b, c, d, e, f, g, h)


```

```{r}
Mm.scRNA_scran.norm <- readRDS("E:/Islet project data-Jayesh/Human islet scRNA JT/Working RDS flies/HIRN Alpha 0.03 JT.rds")
Mm.scRNA_scran.norm <- SetIdent(Mm.scRNA_scran.norm,  value = Mm.scRNA_scran.norm$subtype2_condition)
Mm.scRNA_scran.norm <- SetIdent(Mm.scRNA_scran.norm,  value = Mm.scRNA_scran.norm$all_cell_diet_week)
```

```{r}
cluster.name <- "Hs-Alpha 1"
sheet_name <- "3"
GSEA.sheet.sorted <- readxl::read_excel("D:/Islet Project/Updated data 20012023/Sheets/GSEA_pathway_list_mouse.xlsx", sheet = "Mm.Alpha 1")
idents_to_use <- c("Hs-Alpha 1_Control", "Hs-Alpha 1_Obese","Hs-Alpha 1_T2D")
#########################################################################################################################################
genesets.subset <- genesets[unique(GSEA.sheet.sorted$names.genesets.)]

Mm.scRNA_scran.norm.subset <- subset(Mm.scRNA_scran.norm, subtype2 == cluster.name) 

logfc.data <- logFC(cluster.ids=Mm.scRNA_scran.norm.subset@meta.data$subtype2_condition ,expr.mat=Mm.scRNA_scran.norm.subset@assays$RNA@data)

names(logfc.data)

gse.res <- wmw_gsea(expr.mat=Mm.scRNA_scran.norm.subset@assays$RNA@data,
                    cluster.cells=logfc.data[[1]],log.fc.cluster=logfc.data[[2]],gene.sets= genesets.subset)

####################################################################################################################################################################################
cluster.name <- "Mm-Beta 1"
sheet_name <- "3"
GSEA.sheet.sorted <- readxl::read_excel("E:/Islet Project/Updated data 20012023/Sheets/Mm.Beta 1/Beta 1 selected pathway", sheet = 3)
idents_to_use <- c("Mm-Beta 1 RC_8W", "Mm-Beta 1 RC_14W","Mm-Beta 1 RC_22W","Mm-Beta 1 HFD_8W","Mm-Beta 1 HFD_16W")
#########################################################################################################################################
genesets.subset <- genesets[unique(GSEA.sheet.sorted$names.genesets.)]

Mm.scRNA_scran.norm.subset <- subset(Mm.scRNA_scran.norm, cellstates.updated == cluster.name) 

logfc.data <- logFC(cluster.ids=Mm.scRNA_scran.norm.subset@meta.data$cellstates.diet.week.updated ,expr.mat=Mm.scRNA_scran.norm.subset@assays$RNA@data)

names(logfc.data)

gse.res <- wmw_gsea(expr.mat=Mm.scRNA_scran.norm.subset@assays$RNA@data,
                    cluster.cells=logfc.data[[1]],log.fc.cluster=logfc.data[[2]],gene.sets= genesets.subset)
###################################################################################################################################################
cluster.name <- "Mm-Vascular endothelial"
sheet_name <- "Mm.Vascular endothelial"
GSEA.sheet.sorted <- readxl::read_excel("E:/Islet Project/Updated data 20012023/Sheets/GSEA_pathway_list_mouse.xlsx", sheet = "Mm.Vascular endothelial")
idents_to_use <- c("Mm-Vascular endothelial RC_8W", "Mm-Vascular endothelial RC_14W","Mm-Vascular endothelial RC_22W","Mm-Vascular endothelial HFD_8W","Mm-Vascular endothelial HFD_16W", "Mm-Vascular endothelial HFD_24W" )
#########################################################################################################################################
genesets.subset <- genesets[unique(GSEA.sheet.sorted$names.genesets.)]

Mm.scRNA_scran.norm.subset <- subset(Mm.scRNA_scran.norm, beta_sub_subpopulations == cluster.name) 

  logfc.data <- logFC(cluster.ids=Mm.scRNA_scran.norm.subset@meta.data$all_cell_diet_week ,expr.mat=Mm.scRNA_scran.norm.subset@assays$RNA@data)

names(logfc.data)

gse.res <- wmw_gsea(expr.mat=Mm.scRNA_scran.norm.subset@assays$RNA@data,
                    cluster.cells=logfc.data[[1]],log.fc.cluster=logfc.data[[2]],gene.sets= genesets.subset)
```

```{r}

res.stats <- gse.res[["GSEA_statistics"]]
res.pvals <- gse.res[["GSEA_p_values"]]

res.pvals <- apply(res.pvals,2,p.adjust,method="fdr") #Correct for multiple comparisons

res.stats[order(res.stats[,1],decreasing=TRUE)[1:10],] #Top gene sets enriched by z scores

res.pvals[order(res.stats[,1],decreasing=TRUE)[1:10],] #Top gene sets by p values

res.stats.subset <- res.stats[ ,idents_to_use]
res.pvals.subset <- res.pvals[,idents_to_use]
#Plot the z scores with heatmap3
setwd("E:/Islet Project/Final fig/BETA2/")

p3 <- pheatmap::pheatmap(res.stats.subset, scale = "row", border_color = "black", cluster_rows = T, cluster_cols = F, treeheight_row = 0, main = paste0("GSEA: ",cluster.name, " (scaled Z score)"), fontsize_row = 10, angle_col = 315, fontsize_col = 10)

print(p3)

ggsave(plot = p3, filename = "alpha1.tiff",path = "E:/Islet project data-Jayesh/Human islet scRNA JT/Plots and sheets/Hs-Alpha/", units="in", width=8, height=5, dpi=300)

getwgetwd()
```

```{r}
ggsave(p2, "E:/Islet Project/Updated data 20012023/Sheets/GSEA_pathway_list_mouse.xlsx")
```


<!-- ```{r} -->
<!-- res.stats.subset <- res.stats[ ,idents.to.use] -->


<!-- df1 <- melt(data = res.pvals.subset, na.rm = F) -->
<!-- colnames(df1) <- c("Pathways", "Populations", "P val.") -->
<!-- df1$path_pop <- paste0(df1$Pathways," ",df1$Populations) -->


<!-- df2 <- melt(data = as.matrix(res.stats.subset), na.rm = F) -->
<!-- colnames(df2) <- c("Pathways", "Populations", "Z score") -->
<!-- df2$path_pop <- paste0(df2$Pathways," ",df2$Populations) -->


<!-- df3 <- merge(df1, df2, by = "path_pop") -->
<!-- ``` -->

<!-- ```{r} -->
<!-- df <- data.frame( -->
<!--   groups = c(rep("group1",3),rep("group2",3),rep("group3",3)), -->
<!--   genes = rep(c("gene1","gene2","gene3"),3), -->
<!--   exp = rnorm(9,0,10) -->
<!-- ) -->


<!-- ggplot(df3, aes(x = Populations.y, y = Pathways.y, color = `Z score`, size = `P val.`)) +  -->
<!--   geom_point(stat = 'identity') +  -->
<!--   xlab("") + ylab("") + ggtitle(paste0("GSEA: ", cluster.name)) +  -->
<!--   theme_bw() -->
<!-- ``` -->
<!-- ```{r} -->
<!-- dot_plot <- ggplot(df3, aes(x=Populations.y, y=Pathways.y)) + -->
<!--   geom_point(aes(size = `P val.`, fill = `Z score`, scale = "row"), color="black", shape=21) + -->
<!--   scale_size("% detected", range = c(0,6)) + -->
<!--   scale_fill_gradientn(colours = as.factor(c("black", "blue", "yellow", "orange", "pink", "red")), -->
<!--                        guide = guide_colorbar(ticks.colour = "black", -->
<!--                                               frame.colour = "black"), -->
<!--                        name = "Z score") + -->
<!--   ylab("Cluster") + xlab("") + -->
<!--   theme_bw() + -->
<!--   theme(axis.text.x = element_text(size=10, angle=45, hjust=1, color="black"), -->
<!--         axis.text.y = element_text(size=12, color="black"), -->
<!--         axis.title = element_text(size=14)) -->
<!-- ``` -->

